language: node_js
node_js:
- lts/*
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script: "./build.sh"
before_deploy:
  - cd backend
deploy:
  provider: heroku
  app: mooc-part-7
  run:
    - "yarn start"
  skip_cleanup: true
  api_key:
    secure: vEe8S88XDEWR15JktMcRwwv0iLkmJW2wpxpH6Bsxt1PSEz66lTUwtylDCMyTgJc2iwJiqlruQ+8rKvQbiOhKrxm8Otrk3YDCJfev742MHwRLMCssdPe22n7RfYWntjUafHNhXF8UW1AqJ5x0KZ9tNqaPRcWZH1QboR0TxjuyiGoRcltFuTR2l3X514zoIMhT/Bo486tAxJnRYf9Pl5HK4YZ2Si72nvJQBtR1C08Z8Uh0V1BzqcrgtothDsR5B1BQjNoGj74G8X8dAFTvHkIh/7rpsnEYOam6WHftnlxJJZaFYvVzaxUnnzQEGJs4o9M3C5N3hbX/T4vywhCkLIchkCi/Fpv5nsMqbqx8xskZaD8BM/veiLlh/XDBlkI8kbTcd6LEH3+9O4F5j3d35glWzjyvoOPDltPgkeVft1y8Yd0XmZ5m+qpZHYwv55CrHV4l8kERcGX0d8WglnUenUQrew/EeJH7F1XWAIquNq4QSewFebvdxKvn80Pwa4iXaHqwMHhd6yZKcBxsiNeYOsURtEbnFbhhYkWhAV5QXLOnUuh1p4ep72BlLkkz+/ZWGYbuqhRDLqN5e/+j6yhCaiOhz1ItoyjcYpT52HtiQtrAXR/okkN4cCyV8Xrf1roKBiHSTHmP6fiLu9YQ39h58VZmC7i/P9C7jkqVDH0m1FvcpKs=
env:
  global:
  - TEST_PORT: 3002
  - secure: FaIxCcSG44x+94Q4+ZXLE4kv9MdcdOekM46j5JZS4zpmzS5NI9P3vOWjMhc94AmMMf2Brp5nldPHDcB8fsKnpiDpeXJEcm3wIgIBrnPmr7v+bJF3aLFeiIok6MVmzI4is4hILx8KqQ35vHIw5Co3QFw9z/fPwksKUAXKW2HKDH03xY81QSOtMUVQYlEXxTStn0xFEAH1be8Rp0WfqZFi1ArYcs1fzOm0g7AhloMYt4KL3hBw7suFun2eRA89V2gcEsGPbZq479MedV8UUltoXzJNfkmbCbL6GOHlui9s0ikozk3VNWwhWiiiL+qOBSyynwi/tLsRxYTBnxE5rftBPaDHy97o+saQqRpJnWptWQgu8GHGR/rIEU0EP7rRcU62IaLfbhvnpTnP3FjMn4AkZ84/dY9L8kqBZf8W8CPvzEe9p7dN3Il+pT1RrT1Xu85rqm/+E/md9alejT8jXivsE5o6/0zdmkAvG3wbmMmLJA9RMQzHTAFC2jAVQCuGvPmLWWzZBm7i072Waci7knJNvywtrc0PpycgF7lVPVRc1fsIA7rwOwayVlPVCpx9S27P1ua/jHMH+VhZpnawPt2QA2jeunwRRHGN0d/iKKcejjRIkB0ifva7rJ77QE3VrxPKVSLv/37oCRGSJRVJS0gzTTuNI0H3m94fS6mcXjtFgZ4=
  - secure: zCm+va+bDHLHFm6rQnEFF0h6dwj/CxDB2arBObwDD5igW0P2nQL4cZiRsqON+c/Gmn20GbOvMDbOQpvIEXNKvlTUyfFI7mRzQMyq/Lp+Tkr3suM/UKuLJdyJO/lUDLKXnoBOz1Ydkq3EZ88J0sNatwfbBBbGxxNDQzivi2Xp2O/y1NjbXzf3MeaVEsljjZWGXS5j+tGKzRCJVvl+fAvQgbInUjQlbJH67AH7qN3xYXTfeKGXpdqpWoTyI6lmgqopdnAKeHbW+8gCX9VnwzIBLwlQIBFzIMVTszA+suf6OzRXpu8jifcLhfctxRwCXO5aBFySoJwuB/z1Pq26iuRpB69gfAf+pUhvThxrVe72rp8602iI+P4pWqojf2uU1FRHY9M7CzCTYFTUxSilr+k9HP5loRMuCQ+gUaZjN2T6qKniIBNDJls+Pi5Ke6KCk9P33lvtZOC5TvYH3PGB8iRefMVIVn3t3b2wZ5GjLkmpUIXz8RkdkWZsavDmoEGdbPRsbk62gyy0RKyl9JcDlR3fnWavc7Y6JEUAHiYUmFkH1tyGOfAiW9M/x/azU8T5zCnpBKlsVqncyXbXgezyG5/g1hlWGk9qlC2gmvE9kgKGlSMk9DqeO4lNISxB8TBCYkFY5oloSnRjgeAiD5hnAqMsp3s0xeqG+EHQ3RJc+JAJD3k=
